### ISSUE TITLE
Upload package.json to editor

### ISSUE THREAD

**Issue by gz65555** [galacean/vscode-extension#10]

**Comment by Sway007** [comment]
Project dependency info is stored in the dependencies field of the project details api reponse.
https://oneapi.alipay.com/app/oasisbe/tag/doc/sprint_oasisbe_S09001620557_20230601?method=ProjectController.detail&source=ZAPPINFO
![image](https://github.com/galacean/vscode-extension/assets/3755521/37cbd74c-d5a7-4df8-b753-987a072df82c)
