### ISSUE TITLE
Click project show request error

### ISSUE THREAD

**Issue by gz65555** [galacean/vscode-extension#15]
How to set server host?
![image](https://github.com/galacean/vscode-extension/assets/6926263/67d8b362-68c1-4fe6-94b8-2d38806c3c55)

And the ui should show the default host

**Comment by Sway007** [comment]
The server address configuration only exists in the beta version of the plugin, and only For internal developer. in the official release, there is no configuration for server host and no need to configure the server address. The default is the online production environment address.

**Comment by Sway007** [comment]
The server host domain address of each enviroment can be found in https://yuyan.antfin-inc.com/OasisHub/oasisbe/sprints
